pool:
  vmImage: windows-latest

variables:
  - template: variables/main.yml

resources:
  containers:
  - container: mongo
    image: mongo
    ports:
    - 27017:27017

stages:
  - stage: Deploy
    jobs:
      - job: Deploy

        steps:
          - template: templates/checkout-and-cache.yml

          - task: ArchiveFiles@2
            displayName: 'Archive Build Artifacts'

            inputs:
              rootFolderOrFile: '.'
              includeRootFolder: false
              archiveType: 'tar'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'

            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
              ArtifactName: '$(APP_FOLDER_NAME)-artifact'
              publishLocation: 'Container'
