pool:
  vmImage: windows-latest

variables:
- template: variables/main.yml
- template: variables/checkout-and-cache.yml

# Disable triggering RP model run by code change
trigger: none

schedules:
- cron: '0 12 * * 0'
  displayName: Weekly Run
  branches:
    include:
    - main
  always: true

stages:
- stage: Deploy
  jobs:
  - job: Deploy

    steps:
    - template: templates/checkout-and-cache.yml

    - script: |
        git config --global user.email "raenonx0710@gmail.com"
        git config --global user.name "RaenonX (RP Model Automation)"
      displayName: 'Set Git Credentials'
      workingDirectory: $(System.DefaultWorkingDirectory)

    - script: py run_rp_model.py
      displayName: 'Run RP Model'

    - script: |
        git checkout -b main
        git add -A
        git commit -m "[AUTO] RP Model Pickle Refresh"
        git push --set-upstream origin main -f
      displayName: Commit & Push
      workingDirectory: $(System.DefaultWorkingDirectory)
